### ISSUE TITLE
Enhance git repo move

### ISSUE THREAD

**Issue by nunomdc** [alichtman/shallow-backup#168]
An error is thrown when moving the git repository if one already exists on the output directory.

``` 
(shallow-backup) $ ls -a ~/sh-back
.  ..  .git  .gitignore
(shallow-backup) $ ls -a ~/sh-back-2
.  ..  .git  .gitignore
(shallow-backup) $ python shallow_backup/cli.py


              dP                dP dP                        dP                         dP
              88                88 88                        88                         88
     ,d8888'  88d888b. .d8888b. 88 88 .d8888b. dP  dP  dP    88d888b. .d8888b. .d8888b. 88  .dP  dP    dP 88d888b.
     Y8ooooo, 88'  `88 88'  `88 88 88 88'  `88 88  88  88    88'  `88 88'  `88 88'  `"" 88888"   88    88 88'  `88
           88 88    88 88.  .88 88 88 88.  .88 88.88b.88'    88.  .88 88.  .88 88.  ... 88  `8b. 88.  .88 88.  .88
     `88888P' dP    dP `88888P8 dP dP `88888P' 8888P Y8P     88Y8888' `88888P8 `88888P' dP   `YP `88888P' 88Y888P'
                                                                                                          88
                                                                                                          dP	
	v1.4a by Aaron Lichtman (@alichtman)

Current shallow-backup path: /home/nunomdc/sh-back
[?] Would you like to update this?:  Yes
 >  Yes
    No

Enter relative or absolute path:
~/sh-back-2

Updating shallow-backup path to /home/nunomdc/sh-back-2
Traceback (most recent call last):
  File "shallow_backup/cli.py", line 180, in <module>
    cli()
  File "/home/nunomdc/.local/share/virtualenvs/shallow-backup-zRzFi1jy/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/nunomdc/.local/share/virtualenvs/shallow-backup-zRzFi1jy/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/nunomdc/.local/share/virtualenvs/shallow-backup-zRzFi1jy/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nunomdc/.local/share/virtualenvs/shallow-backup-zRzFi1jy/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "shallow_backup/cli.py", line 79, in cli
    prompt_for_path_update(backup_config)
  File "/home/nunomdc/repos/shallow-backup/shallow_backup/prompts.py", line 25, in prompt_for_path_update
    move_git_repo(current_path, abs_path)
  File "/home/nunomdc/repos/shallow-backup/shallow_backup/git_wrapper.py", line 99, in move_git_repo
    move(git_dir, new_path)
  File "/home/nunomdc/.local/share/virtualenvs/shallow-backup-zRzFi1jy/lib/python3.6/shutil.py", line 542, in move
    raise Error("Destination path '%s' already exists" % real_dst)
shutil.Error: Destination path '/home/nunomdc/sh-back-2/.git' already exists
```

**Comment by alichtman** [comment]
To fix this, we should make sure that the path doesn't exist before copying it. I believe the method responsible for moving the git repo is in `git-wrapper.py`, potentially called `move_git_repo()`, but I'm not sure.

**Comment by nunomdc** [comment]
What would be the expected behaviour on error?
* exit the application
* prompt for overwrite
* other option

**Comment by alichtman** [comment]
> If it does exist, print an error message and exit.

**Comment by nunomdc** [comment]
> If it does exist, print an error message and exit.

Ok. So should we exit early, as soon as the issue is detected?
Have a look at this commit https://github.com/nunomdc/shallow-backup/commit/6b27205f5e74ba4696a1ca6cf073db2633a4f8d9

**Comment by alichtman** [comment]
Open a PR so I can leave comments on specific lines. That commit is close, but not exactly how I think this feature should work.
