### ISSUE TITLE
gitpython Not Installed Automatically w/ setup.py

### ISSUE THREAD

**Issue by AlexanderProd** [alichtman/shallow-backup#200]
I've installed shallow-backup using pip3 
`$ pip3 install shallow-backup`

But running shallow-backup throws this error
```
Traceback (most recent call last):
  File "/usr/local/bin/shallow-backup", line 7, in <module>
    from shallow_backup.__main__ import cli
  File "/usr/local/lib/python3.7/site-packages/shallow_backup/__main__.py", line 3, in <module>
    from .prompts import *
  File "/usr/local/lib/python3.7/site-packages/shallow_backup/prompts.py", line 7, in <module>
    from .git_wrapper import git_set_remote, move_git_repo
  File "/usr/local/lib/python3.7/site-packages/shallow_backup/git_wrapper.py", line 3, in <module>
    import git
ModuleNotFoundError: No module named 'git'
```

I've got git installed and it is working on my mac though. 
Python3 is installed via brew.

Python version: 3.7.1
pip3: 18.1
macOS: 10.14.2

**Comment by alichtman** [comment]
This is a seemingly confusing error with an easy fix.

To fix this, you should run `pip3 install gitpython`, however, this should be installed automatically when you run `pip3 install shallow-backup`.

I'm filing this as a bug, and I'll look into fixing it when I have some time.

**Comment by AlexanderProd** [comment]
Thanks this fixed it I've opened a PR including the changes.

**Comment by alichtman** [comment]
Awesome, thanks man.
