### ISSUE TITLE
Unable to run macOS

### ISSUE THREAD

**Issue by uhlhosting** [alichtman/shallow-backup#235]
```
➜ shallow-backup 
Traceback (most recent call last):
  File "/usr/local/bin/shallow-backup", line 6, in <module>
    from shallow_backup.__main__ import cli
  File "/Library/Python/2.7/site-packages/shallow_backup/__main__.py", line 2, in <module>
    from .backup import *
  File "/Library/Python/2.7/site-packages/shallow_backup/backup.py", line 2, in <module>
    from shlex import quote
ImportError: cannot import name quote

14:18:22.457 in /Library/Python  

```

**Comment by alichtman** [comment]
Looks like you’re using Python 2.7, which is unsupported. You should follow the installation instructions in the README which will show you how to install this to use Python 3.X.

**Comment by uhlhosting** [comment]
I did installed with pip3.

**Comment by alichtman** [comment]
Well. As a quick fix, you can git clone this and run $ python3 setup.py install
