### ISSUE TITLE
🙋‍♀️ running shallow-backup interactively (backup all) does not save to the folder

### ISSUE THREAD

**Issue by jasikpark** [alichtman/shallow-backup#282]
I just installed shallow-backup via pip3 on macOS 10.15.6 and ran it with `shallow-backup` and it did not backup. I finally got it to work with `shallow-backup -backup-all` and it worked? But selecting `backup all` in the interactive mode did not work for me, it exited without output.

shallow-backup -show:
```

[31m[1m#######################
# SHALLOW BACKUP CONFIG
#######################
[0m
[31m[1mBackup Path: [22m/Users/calebjasik/shallow-backup[0m
[31m[1m
Dotfiles: [22m(Backup and Reinstall conditions will be shown if they exist)[0m
	.bash_profile
	.bashrc
	.config/git
	.config/nvim/init.vim
	.config/tmux
	.config/zsh
	.profile
	.pypirc
	.ssh
	.zshenv
	.config/shallow-backup.conf
[31m[1m
Root gitignore: [0m
	dotfiles/.ssh
	dotfiles/.pypirc
	.DS_Store
[31m[1m
Dotfiles gitignore: [0m
	.ssh
	.pypirc
	.DS_Store
[31m[1m
Configs:[0m
	/Users/calebjasik/Library/Application Support/Sublime Text 2 -> sublime2
	/Users/calebjasik/Library/Application Support/Sublime Text 3 -> sublime3
	/Users/calebjasik/Library/Application Support/Code/User/settings.json -> vscode/settings
	/Users/calebjasik/Library/Application Support/Code/User/Snippets -> vscode/Snippets
	/Users/calebjasik/Library/Application Support/Code/User/keybindings.json -> vscode/keybindings
	/Users/calebjasik/.atom -> atom
	/Users/calebjasik/Library/Preferences/com.apple.Terminal.plist -> terminal_plist
[31m[1mLowest supported version: [22m5.0.1[0m
```

**Comment by jasikpark** [comment]
Whereas `shallow-backup -backup-all` works fine?

```shell
$ % shallow-backup -backup-all


              dP                dP dP                        dP                         dP
              88                88 88                        88                         88
     ,d8888'  88d888b. .d8888b. 88 88 .d8888b. dP  dP  dP    88d888b. .d8888b. .d8888b. 88  .dP  dP    dP 88d888b.
     Y8ooooo, 88'  `88 88'  `88 88 88 88'  `88 88  88  88    88'  `88 88'  `88 88'  `"" 88888"   88    88 88'  `88
           88 88    88 88.  .88 88 88 88.  .88 88.88b.88'    88.  .88 88.  .88 88.  ... 88  `8b. 88.  .88 88.  .88
     `88888P' dP    dP `88888P8 dP dP `88888P' 8888P Y8P     88Y8888' `88888P8 `88888P' dP   `YP `88888P' 88Y888P'
                                                                                                          88
                                                                                                          dP	
	v5.0.1 by Aaron Lichtman (@alichtman)

Detected git repo.
Updating .gitignore file at /Volumes/UNTITLED/shallow-backup/.gitignore with config from root-gitignore
Updating .gitignore file at /Volumes/UNTITLED/shallow-backup/dotfiles/.gitignore with config from dotfiles-gitignore

##########
# DOTFILES
##########

Creating: /Volumes/UNTITLED/shallow-backup/dotfiles
Creating: /Volumes/UNTITLED/shallow-backup/dotfiles
Creating: /Volumes/UNTITLED/shallow-backup/dotfiles/.config
Creating: /Volumes/UNTITLED/shallow-backup/dotfiles/.config/nvim
Creating: /Volumes/UNTITLED/shallow-backup/dotfiles/.config
Creating: /Volumes/UNTITLED/shallow-backup/dotfiles/.config
Creating: /Volumes/UNTITLED/shallow-backup/dotfiles
Creating: /Volumes/UNTITLED/shallow-backup/dotfiles
Creating: /Volumes/UNTITLED/shallow-backup/dotfiles
Creating: /Volumes/UNTITLED/shallow-backup/dotfiles/.config
Creating: /Volumes/UNTITLED/shallow-backup/dotfiles
Backing up dotfolders...
Backing up dotfiles...
Process Process-6:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/calebjasik/.bash_profile'
Process Process-7:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/calebjasik/.bashrc'
Process Process-8:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/calebjasik/.config/git'
Process Process-9:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/calebjasik/.config/nvim/init.vim'
Process Process-10:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/calebjasik/.config/tmux'
Process Process-11:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/calebjasik/.config/zsh'
Process Process-13:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/calebjasik/.pypirc'
Process Process-14:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/calebjasik/.zshenv'

##########
# PACKAGES
##########

Backing up brew packages list...
Backing up brew cask packages list...
Backing up gem packages list...
Backing up cargo packages list...
Backing up pip packages list...
An error occurred while running: $ pip list --format=freeze
Backing up pip3 packages list...
Backing up npm packages list...
Backing up Atom packages list...
An error occurred while running: $ apm list --installed --bare
Backing up VSCode packages list...
Backing up macports packages list...
An error occurred while running: $ port installed requested
Backing up System Applications packages list...

#######
# FONTS
#######

Copying '.otf' and '.ttf' fonts...

#########
# CONFIGS
#########

Backing up configs...
Making new commit...
Successful commit.
```

**Comment by jasikpark** [comment]
also: ?????
```
       │ File: pip3_list.txt
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ /usr/local/lib
   2   │ /usr/local/lib/node_modules/@fraction/oasis
   3   │ /usr/local/lib/node_modules/a11y
   4   │ /usr/local/lib/node_modules/autoprefixer
   5   │ /usr/local/lib/node_modules/broken-link-checker
   6   │ /usr/local/lib/node_modules/create-elm-app
   7   │ /usr/local/lib/node_modules/elm
   8   │ /usr/local/lib/node_modules/elm-format
   9   │ /usr/local/lib/node_modules/elm-test
  10   │ /usr/local/lib/node_modules/gitignore-it
  11   │ /usr/local/lib/node_modules/katex
  12   │ /usr/local/lib/node_modules/moon-cli
  13   │ /usr/local/lib/node_modules/netlify-cli
  14   │ /usr/local/lib/node_modules/npm
  15   │ /usr/local/lib/node_modules/postcss-cli
```

**Comment by alichtman** [comment]
Well, this seems like a problem. Unfortunately, I don't have time to dig deep into it right now.

**Comment by jasikpark** [comment]
It will be interesting if replicated after I reset my computer, since the reason I've reinstalled this tool again is to make shallow backups of my stuff before I wipe my machine

**Comment by alichtman** [comment]
I'm sure you know this already, but I'd strongly recommend having a complete TimeMachine backup as a redundancy measure, in case there's some weird issue with `shallow-backup` (like this :)).

**Comment by jasikpark** [comment]
True, true. I’m currently waiting for the second hour of my machine to finish a Time Machine backup… but I verified that it created the files I needed — I mostly wanted to use this for the backup creation, less so the automated restoration.

Caleb Jasik
calebjasik@jasik.xyz
https://jasik.xyz

On September 12, 2020 at 10:25:51 PM, Aaron Lichtman (notifications@github.com) wrote:

I'm sure you know this already, but I'd strongly recommend having a complete TimeMachine backup as a redundancy measure, in case there's some weird issue with shallow-backup (like this :)).

**Comment by alichtman** [comment]
My workflow depends on both the automated backup and restoration (and I've built out a fairly comprehensive testing suite to catch errors), so this bug is concerning. I've got way too much on my plate at the moment to give you any sort of estimate for when I'll get to this, but it's on my radar. Thanks for reporting this.

**Comment by jasikpark** [comment]
sounds good

**Comment by tim-coutinho** [comment]
With regards to https://github.com/alichtman/shallow-backup/issues/282#issuecomment-691525613, the issue is [here](https://github.com/alichtman/shallow-backup/blob/master/shallow_backup/backup.py#L171). The npm backup step is using `dest` in line with the rest of the backup steps, but it should be using `temp_file_path`, resulting in it overwriting the pip3 step right before it. I'd create a PR myself for this tiny change, but I'm having some permission issues for whatever reason.

**Comment by alichtman** [comment]
@tim-coutinho Having permission issues creating the PR or when testing the code? I'm happy to help with either

**Comment by alichtman** [comment]
Let's make a new issue for it and just tags this issue in a comment. I try to keep a separate branch for each feature / bug fix for a more useful git history

**Comment by tim-coutinho** [comment]
Getting a 503 when trying to push my local branch to remote, tried my work machine and personal machine as well as cloning via https and ssh, no dice. I'll create a new issue.

**Comment by alichtman** [comment]
I don’t believe you have write privileges for this repo, however, if you
fork the project, push to your remote and open a PR, you should be golden.

**Comment by alichtman** [comment]
Seems like this was resolved.
