### ISSUE TITLE
Bug - dotfiles fail to save `[Errno 2] No such file or directory:`

### ISSUE THREAD

**Issue by jasikpark** [alichtman/shallow-backup#297]
## Stats:

- shallow-backup@v5.0.1
- macOS 11.6
- python 3.9

## Bug

Ran `shallow-backup -backup-all`

got 

```sh
✗  shallow-backup -backup-all


              dP                dP dP                        dP                         dP
              88                88 88                        88                         88
     ,d8888'  88d888b. .d8888b. 88 88 .d8888b. dP  dP  dP    88d888b. .d8888b. .d8888b. 88  .dP  dP    dP 88d888b.
     Y8ooooo, 88'  `88 88'  `88 88 88 88'  `88 88  88  88    88'  `88 88'  `88 88'  `"" 88888"   88    88 88'  `88
           88 88    88 88.  .88 88 88 88.  .88 88.88b.88'    88.  .88 88.  .88 88.  ... 88  `8b. 88.  .88 88.  .88
     `88888P' dP    dP `88888P8 dP dP `88888P' 8888P Y8P     88Y8888' `88888P8 `88888P' dP   `YP `88888P' 88Y888P'
                                                                                                          88
                                                                                                          dP
	v5.0.1 by Aaron Lichtman (@alichtman)

Detected git repo.
Updating .gitignore file at /Users/calebjasik/shallow-backup/.gitignore with config from root-gitignore
Updating .gitignore file at /Users/calebjasik/shallow-backup/dotfiles/.gitignore with config from dotfiles-gitignore

##########
# DOTFILES
##########

Creating: /Users/calebjasik/shallow-backup/dotfiles
Creating: /Users/calebjasik/shallow-backup/dotfiles
Creating: /Users/calebjasik/shallow-backup/dotfiles/.config
Creating: /Users/calebjasik/shallow-backup/dotfiles/.config/nvim
Creating: /Users/calebjasik/shallow-backup/dotfiles/.config
Creating: /Users/calebjasik/shallow-backup/dotfiles/.config
Creating: /Users/calebjasik/shallow-backup/dotfiles
Creating: /Users/calebjasik/shallow-backup/dotfiles
Creating: /Users/calebjasik/shallow-backup/dotfiles
Creating: /Users/calebjasik/shallow-backup/dotfiles/.config
Creating: /Users/calebjasik/shallow-backup/dotfiles
Backing up dotfolders...
Backing up dotfiles...
Process Process-6:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/calebjasik/.bash_profile'
Process Process-8:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/calebjasik/.config/git'
Process Process-9:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/calebjasik/.config/nvim/init.vim'
Process Process-10:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/calebjasik/.config/tmux'
Process Process-11:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/calebjasik/.config/zsh'
Process Process-13:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/calebjasik/.pypirc'
‰Process Process-14:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/calebjasik/.zshenv'

##########
# PACKAGES
##########

Backing up brew packages list...
Backing up brew cask packages list...
An error occurred while running: $ brew cask list
Backing up gem packages list...
Backing up cargo packages list...
Backing up pip packages list...
An error occurred while running: $ pip list --format=freeze
Backing up pip3 packages list...
Backing up npm packages list...
Backing up Atom packages list...
An error occurred while running: $ apm list --installed --bare
Backing up VSCode packages list...
Backing up macports packages list...
An error occurred while running: $ port installed requested
Backing up System Applications packages list...

#######
# FONTS
#######

Copying '.otf' and '.ttf' fonts...

#########
# CONFIGS
#########

Backing up configs...
Making new commit...
Successful commit.
~ took 1m8s
➜  ‰[Errno 2] No such file or directory:
```

<details>
<summary>`.config/shallow-backup.conf`</summary>

```sh
{
    "backup_path": "~/shallow-backup",
    "dotfiles": {
        ".bash_profile": {
            "backup_condition": "",
            "reinstall_condition": ""
        },
        ".bashrc": {
            "backup_condition": "",
            "reinstall_condition": ""
        },
        ".config/git": {
            "backup_condition": "",
            "reinstall_condition": ""
        },
        ".config/nvim/init.vim": {
            "backup_condition": "",
            "reinstall_condition": ""
        },
        ".config/tmux": {
            "backup_condition": "",
            "reinstall_condition": ""
        },
        ".config/zsh": {
            "backup_condition": "",
            "reinstall_condition": ""
        },
        ".profile": {
            "backup_condition": "",
            "reinstall_condition": ""
        },
        ".pypirc": {
            "backup_condition": "",
            "reinstall_condition": ""
        },
        ".ssh": {
            "backup_condition": "",
            "reinstall_condition": ""
        },
        ".zshenv": {
            "backup_condition": "",
            "reinstall_condition": ""
        },
        ".config/shallow-backup.conf": {
            "backup_condition": "",
            "reinstall_condition": ""
        }
    },
    "root-gitignore": [
        "dotfiles/.pypirc",
        ".DS_Store"
    ],
    "dotfiles-gitignore": [
        ".pypirc",
        ".DS_Store"
    ],
    "config_mapping": {
        "/Users/calebjasik/Library/Application Support/Sublime Text 2": "sublime2",
        "/Users/calebjasik/Library/Application Support/Sublime Text 3": "sublime3",
        "/Users/calebjasik/Library/Application Support/Code/User/settings.json": "vscode/settings",
        "/Users/calebjasik/Library/Application Support/Code/User/Snippets": "vscode/Snippets",
        "/Users/calebjasik/Library/Application Support/Code/User/keybindings.json": "vscode/keybindings",
        "/Users/calebjasik/.atom": "atom",
        "/Users/calebjasik/Library/Preferences/com.apple.Terminal.plist": "terminal_plist"
    },
    "lowest_supported_version": "5.0.1"
}
```

</details>

**Comment by alichtman** [comment]
Does `/Users/calebjasik/.bash_profile` exist?

**Comment by jasikpark** [comment]
Ah, nope I've got zsh

**Comment by jasikpark** [comment]
I'll see about configuring this more carefully :( I kinda assumed the default config would just pull everything & not fail if something didn't exist on my system

**Comment by alichtman** [comment]
From the perspective of a backup system, it IS an error if a file we’re
supposed to be backing up (as defined in the config) doesn’t exist. The
error could definitely be displayed in a more user friendly way though.
Want to put up a patch?
