### ISSUE TITLE
Error? Or do I just not know how to use this.

### ISSUE THREAD

**Issue by yelled1** [alichtman/shallow-backup#54]
Hi:

Having issues backing up. Trying to backup to iCloud.
Thanks,

Hoon,

```shell
$cat .shallow-backup
[USER]
#backup_path = DEFAULT
backup_path = /Users/hoon/Library/Mobile Documents/com~apple~CloudDocs/Shallow_Bkup
```
```
[?] Would you like to update this?:  No
    Yes
 >  No

CREATED DIR: /Users/hoon/Library/Mobile Documents/com~apple~CloudDocs/Shallow_Bkup
/Users/hoon/Library/Mobile Documents/com~apple~CloudDocs/Shallow_Bkup/packages
[?] What would you like to do?:  Back up dotfiles
 >  Back up dotfiles
    Back up packages
    Back up fonts
    Back up everything
    Reinstall packages
##########
('#', 'DOTFILES')
##########

CREATED DIR: /Users/hoon/Library/Mobile Documents/com~apple~CloudDocs/Shallow_Bkup/dotfiles
Traceback (most recent call last):
  File "/usr/local/bin/shallow-backup", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/shallow_backup.py", line 491, in cli
    backup_dotfiles(dotfiles_path)
  File "/usr/local/lib/python2.7/site-packages/shallow_backup.py", line 195, in backup_dotfiles
    with mp.Pool(mp.cpu_count()):
AttributeError: __exit__
```

**Comment by yelled1** [comment]
Tried to install with pip3 but now I get stopped on npm
```
pip3 install shallow-backup
Collecting shallow-backup
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/da/f2/676f83affd33f639ee669327ccf14a415516282667555a8863627e1f4c2c/shallow_backup-1.3-py2.py3-none-any.whl
Collecting inquirer>=2.2.0 (from shallow-backup)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/bd/b8/0b04f23f7870f96c81bdf9b9863c12985bec0f2738218bcfc67842be4ae8/inquirer-2.2.0-py2.py3-none-any.whl
Collecting Click (from shallow-backup)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Collecting colorama>=0.3.9 (from shallow-backup)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/db/c8/7dcf9dbcb22429512708fe3a547f8b6101c0d02137acbd892505aee57adf/colorama-0.3.9-py2.py3-none-any.whl
Collecting readchar==0.7 (from inquirer>=2.2.0->shallow-backup)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/61/a9/d552ab5bb2978b609a0acc917427fb0230ac923d92e32b817ef79908f6e3/readchar-0.7.tar.gz
Collecting blessings>=1.6 (from inquirer>=2.2.0->shallow-backup)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/03/74/489f85a78247609c6b4f13733cbf3ba0d864b11aa565617b645d6fdf2a4a/blessings-1.7-py3-none-any.whl
Requirement already satisfied: six in /usr/local/lib/python3.6/site-packages (from blessings>=1.6->inquirer>=2.2.0->shallow-backup) (1.11.0)
Building wheels for collected packages: readchar
  Running setup.py bdist_wheel for readchar ... done
  Stored in directory: /Users/hoon/Library/Caches/pip/wheels/f1/67/9f/603400577c2e5725a8b5b0a9a9e01509c24ea6bb022bbf8131
Successfully built readchar
Installing collected packages: readchar, blessings, inquirer, Click, colorama, shallow-backup
Successfully installed Click-6.7 blessings-1.7 colorama-0.3.9 inquirer-2.2.0 readchar-0.7 shallow-backup-1.3
Cache entry deserialization failed, entry ignored
ArthenasMacAir4:~ hoon$ shallow-backup

            dP                dP dP                        dP                         dP
            88                88 88                        88                         88
   ,d8888'  88d888b. .d8888b. 88 88 .d8888b. dP  dP  dP    88d888b. .d8888b. .d8888b. 88  .dP  dP    dP 88d888b.
   Y8ooooo, 88'  `88 88'  `88 88 88 88'  `88 88  88  88    88'  `88 88'  `88 88'  `"" 88888"   88    88 88'  `88
         88 88    88 88.  .88 88 88 88.  .88 88.88b.88'    88.  .88 88.  .88 88.  ... 88  `8b. 88.  .88 88.  .88
   `88888P' dP    dP `88888P8 dP dP `88888P' 8888P Y8P     88Y8888' `88888P8 `88888P' dP   `YP `88888P' 88Y888P'
                                                                                                        88
                                                                                                        dP

------------------------------------------------------------
shallow-backup v1.3 by Aaron Lichtman -> (Github: alichtman)
------------------------------------------------------------

Current shallow-backup path -> /Users/hoon/Library/Mobile Documents/com~apple~CloudDocs/Shallow_Bkup
[?] Would you like to update this?:  No
    Yes
 >  No

/Users/hoon/Library/Mobile Documents/com~apple~CloudDocs/Shallow_Bkup/packages
[?] What would you like to do?:  Back up everything
    Back up dotfiles
    Back up packages
    Back up fonts
 >  Back up everything
    Reinstall packages


##########
# DOTFILES
##########

Directory /Users/hoon/Library/Mobile Documents/com~apple~CloudDocs/Shallow_Bkup/dotfiles already exists

[?] Erase directory and make new back up?:  Yes
 >  Yes
    No

Backing up dotfolders...
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
Backing up dotfiles...
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory

##########
# PACKAGES
##########

CREATED DIR: /Users/hoon/Library/Mobile Documents/com~apple~CloudDocs/Shallow_Bkup/packages
Backing up brew package list...
Error: No available formula with the name "documents/com~apple~clouddocs/shallow_bkup/packages/brew_list.txt"
Backing up brew cask package list...
Error: Cask 'brew-cask_list.txt' is unavailable: No Cask with this name exists.
Backing up gem package list...
Backing up cargo package list...
ls: /Users/hoon/.cargo/bin/: No such file or directory
ls: Documents/com~apple~CloudDocs/Shallow_Bkup/packages/cargo_list.txt: No such file or directory
Backing up pip package list...
Backing up npm package list...
Traceback (most recent call last):
  File "/usr/local/bin/shallow-backup", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/shallow_backup.py", line 489, in cli
    backup_all(dotfiles_path, packages_path, fonts_path)
  File "/usr/local/lib/python3.6/site-packages/shallow_backup.py", line 308, in backup_all
    backup_packages(packages_path)
  File "/usr/local/lib/python3.6/site-packages/shallow_backup.py", line 240, in backup_packages
    with open("{0}/npm_temp_list.txt".format(backup_path), mode="r+") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hoon/Library/Mobile Documents/com~apple~CloudDocs/Shallow_Bkup/packages/npm_temp_list.txt'
```

**Comment by alichtman** [comment]
Hmm. Let me take a look at this later today and see what I can come up with. Nothing's jumping out at me right now.

**Comment by alichtman** [comment]
That's a file not found error. Maybe you moved the folder and didn't update the file path in `~.shallow-backup`?
