### ISSUE TITLE
Default install missing ConfigParser dependency?

### ISSUE THREAD

**Issue by ChrisWeiss** [alichtman/shallow-backup#62]
Not a lot of Python experience, but after doing pip install and trying to run shallow-backup, it complains about missing module configparser. Manually doing `pip install configparser` does fix the issue.

```$ pip install shallow-backup
Collecting shallow-backup
  Downloading https://files.pythonhosted.org/packages/da/f2/676f83affd33f639ee669327ccf14a415516282667555a8863627e1f4c2c/shallow_backup-1.3-py2.py3-none-any.whl
Collecting Click (from shallow-backup)
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
    100% |████████████████████████████████| 81kB 6.2MB/s
Collecting inquirer>=2.2.0 (from shallow-backup)
  Downloading https://files.pythonhosted.org/packages/5b/e1/1b154d3f81af4e33c35270a19bd2b26d85466aa131781f5eda175af19a1c/inquirer-2.5.1-py2.py3-none-any.whl
Collecting colorama>=0.3.9 (from shallow-backup)
  Downloading https://files.pythonhosted.org/packages/db/c8/7dcf9dbcb22429512708fe3a547f8b6101c0d02137acbd892505aee57adf/colorama-0.3.9-py2.py3-none-any.whl
Collecting readchar>=2.0.0 (from inquirer>=2.2.0->shallow-backup)
  Downloading https://files.pythonhosted.org/packages/e9/63/9e8c21d675871c60377dbad2e3a3e44135d1bfd25aeb48f0f392a9f09bfd/readchar-2.0.1-py2-none-any.whl
Collecting blessings>=1.7 (from inquirer>=2.2.0->shallow-backup)
  Downloading https://files.pythonhosted.org/packages/8d/b1/a3fe6fd8a012e6d019bafd671c2fee0597ea97ff2e76c25aadfa4545fc32/blessings-1.7-py2-none-any.whl
Requirement already satisfied: six in /usr/local/lib/python2.7/site-packages (from blessings>=1.7->inquirer>=2.2.0->shallow-backup) (1.10.0)
Installing collected packages: Click, readchar, blessings, inquirer, colorama, shallow-backup
Successfully installed Click-7.0 blessings-1.7 colorama-0.3.9 inquirer-2.5.1 readchar-2.0.1 shallow-backup-1.3

$ shallow-backup
Traceback (most recent call last):
  File "/usr/local/bin/shallow-backup", line 7, in <module>
    from shallow_backup import cli
  File "/usr/local/lib/python2.7/site-packages/shallow_backup.py", line 9, in <module>
    import configparser
ImportError: No module named configparser```

**Comment by alichtman** [comment]
Try installing with `$ pip3 install shallow-backup`

You should also be running this with Python 3.

ConfigParser is a [built-in module](https://docs.python.org/3/library/configparser.html).
